src/web/common/models/Pago.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "pago".
 *
 * @property integer $id_pago
 * @property integer $id_cuota
 * @property string $monto_pago
 * @property string $fecha_pago
 * @property string $fecha_creacion
 * @property integer $id_usuario
 *
 * @property CondicionPago $idCuota
 * @property User $idUsuario
 */
class Pago extends \yii\db\ActiveRecord
{
    public $total;
    /**
     * @inheritdoc
     */
    
    public static function tableName()
    {
        return 'pago';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_cuota', 'monto_pago', 'fecha_pago', 'fecha_creacion', 'id_usuario'], 'required'],
            [['id_cuota', 'id_usuario'], 'integer'],
            [['monto_pago'], 'number'],
            [['fecha_pago', 'fecha_creacion'], 'safe'],
            [['id_cuota'], 'exist', 'skipOnError' => true, 'targetClass' => CondicionPago::className(), 'targetAttribute' => ['id_cuota' => 'id_cuota']],
            [['id_usuario'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_usuario' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_pago' => 'Id Pago',
            'id_cuota' => 'Id Cuota',
            'monto_pago' => 'Monto Pagado',
            'fecha_pago' => 'Fecha de Pago',
            'fecha_creacion' => 'Fecha Creacion',
            'id_usuario' => 'Id Usuario',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCuota()
    {
        return $this->hasOne(CondicionPago::className(), ['id_cuota' => 'id_cuota']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUsuario()
    {
        return $this->hasOne(User::className(), ['id' => 'id_usuario']);
    }
    
    public function getTotal()
    {
    return $this->$total;
    }
}

src/web/frontend/models/Pago.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pago".
 *
 * @property integer $id_pago
 * @property integer $id_cuota
 * @property string $monto_pago
 * @property string $fecha_pago
 * @property string $fecha_creacion
 * @property integer $id_usuario
 *
 * @property CondicionPago $idCuota
 * @property User $idUsuario
 * @author Julio Murillo <jmurillo@grudu.org>
 */
class Pago extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pago';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_cuota', 'monto_pago', 'fecha_pago', 'fecha_creacion', 'id_usuario'], 'required'],
            [['id_cuota', 'id_usuario'], 'integer'],
            [['monto_pago'], 'number'],
            [['fecha_pago', 'fecha_creacion'], 'safe'],
            [['id_cuota'], 'exist', 'skipOnError' => true, 'targetClass' => CondicionPago::className(), 'targetAttribute' => ['id_cuota' => 'id_cuota']],
            [['id_usuario'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['id_usuario' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_pago' => 'Id Pago',
            'id_cuota' => 'Id Cuota',
            'monto_pago' => 'Monto Pago',
            'fecha_pago' => 'Fecha Pago',
            'fecha_creacion' => 'Fecha Creacion',
            'id_usuario' => 'Id Usuario',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCuota()
    {
        return $this->hasOne(CondicionPago::className(), ['id_cuota' => 'id_cuota']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUsuario()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'id_usuario']);
    }
}

src/web/frontend/controllers/PagoController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Pago;
use common\models\PagoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PagoController implements the CRUD actions for Pago model.
 */
class PagoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pago models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PagoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
  
    /**
     * Displays a single Pago model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pago model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pago();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_pago]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pago model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
       /**Consulta Pago*/
        $model = $this->findModel($id);

        /**Consulta Cuota asociada al pago*/
        $model3 = \common\models\CondicionPago::findOne($id);

//        $factura=  $model3->id_factura;
        
         /**Consulta factura asociada a la cuota*/
        $model2 = \common\models\Factura::findOne(['id_factura'=> $model3->id_factura]);
        
//         print_r($model2);exit;
//         
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        if ($model->load(Yii::$app->request->post())) {
            
            $model->save();
            
            $acumulado=0;

            $pagos = \common\models\Pago::find()->where(['id_cuota'=>$model->id_cuota])->all();
            
            foreach ($pagos as $rowp) {
                $acumulado= $acumulado + $rowp->monto_pago;
            }
           
            if ($model3->monto_estimado_pago == $acumulado) {
               $model3->id_estatus_pago= 3; 
            }else{
               $model3->id_estatus_pago= 2; 
               
            }
            
            $model3->save();
            
            $cuotas = \common\models\CondicionPago::find()->where(['id_factura'=>$model3->id_factura])->all();
                                            print_r($cuotas);exit;
            $pendientes=0;

            foreach ($cuotas as $rowc) {
                if ($rowc->id_estatus_pago == 2 or $rowc->id_estatus_pago == 1 ) {
                    $pendientes= $pendientes + 1;
                }
            }

            if ($pendientes >= 1 ) {
                $model2->id_estatus= 2; 
            }else {
                $model2->id_estatus= 3; 
               
            }

            $model2->save();
            
            Yii::$app->session->setFlash('success','Pago modificado satisfactoriamente'); 
            
            return $this->redirect(['index']);
//            return $this->redirect(['view', 'id' => $model->id_pago]);
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
                'model2' => $model2,
                'model3' => $model3,
            ]);
        }
    }

    /**
     * Deletes an existing Pago model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pago model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pago the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pago::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/web/frontend/controllers/PagosController.php
<?php
namespace frontend\controllers;

use Yii;
use app\models\Factura;
use yii\web\Controller;
use yii\helpers\ArrayHelper;
use app\models\CondicionPago;

/**
 * Pagos controller
 * @author Julio Murillo <jmurillo@grudu.org>
 */
class PagosController extends Controller
{
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    public function actionIndex() {
        
    }
    
    /**
     * Agregar pagos a la factura
     * @return type
     * @author Julio Murillo <jmurillo@grudu.org>
     */
    public function actionAdd() {
        $dataFac = Factura::find()->all() ;
        $data    = ArrayHelper::map($dataFac, 'id_factura', 'nro_factura') ;

        $factura = null ;
        $cuotas  = null ;
        $pago    = null ;
        $monto   = null ;
        
        if (Yii::$app->request->isPost) {
            $idFactura = Yii::$app->request->post('n_factura') ;
            $factura   = Factura::findOne($idFactura) ;
            $cuotas    = CondicionPago::find()->where(['id_factura' => $idFactura])->all() ;

            if ($cuotas) {

                foreach ($cuotas as $value) {

                    $pagoModel = \app\models\Pago::find()->where(['id_cuota' => $value['id_cuota']])->all() ;

                    if ($pagoModel) {
                        $montos = 0 ;
                        
                        foreach ($pagoModel as $valor) {
                            $montos                   = $montos + $valor['monto_pago'] ;
                            $pago[$value['id_cuota']] = new \app\models\Pago ;
                        }
                        
                        $monto[$value['id_cuota']]['abonado']   = $montos ;
                        $pendiente                              = $value['monto_estimado_pago'] - $montos ;
                        $monto[$value['id_cuota']]['pendiente'] = $pendiente ;
                        
                    } else {
                        
                        $pago[$value['id_cuota']]               = new \app\models\Pago ;
                        $monto[$value['id_cuota']]['abonado']   = 0 ;
                        $monto[$value['id_cuota']]['pendiente'] = $value['monto_estimado_pago'] ;
                    }
                }
            }
        }
        return $this->render('add', [
                    'data'    => $data,
                    'factura' => $factura,
                    'cuotas'  => $cuotas,
                    'pago'    => $pago,
                    'monto'   => $monto,
        ]) ;
    }

    /**
     * Método Ajax para registrar el pago definido por la cuota
     * @author Julio Murillo <jmurillo@grudu.org>
     * @return boolean
     */
    public function actionPay() {
        $id_cuota             = Yii::$app->request->post('id_cuota') ;
        $monto                = Yii::$app->request->post('monto') ;
        $fecha                = Yii::$app->request->post('fecha') ;
        $pago                 = new \app\models\Pago() ;
        $pago->id_cuota       = $id_cuota ;
        $pago->monto_pago     = $monto ;
        $pago->fecha_pago     = $fecha ;
        $pago->fecha_creacion = date('Y-m-d') ;
        $pago->id_usuario     = \Yii::$app->user->id ;

        $pagoModel = \app\models\Pago::find()->where(['id_cuota' => $id_cuota])->all() ;
        $montos    = 0 ;
        
        if ($pagoModel) {
            
            foreach ($pagoModel as $valor) {
                $montos = $montos + $valor['monto_pago'] ;
            }
        }
        
        $total = $montos + $monto ;
        $cuota = CondicionPago::findOne($id_cuota) ;
        
        if ($total <= $cuota->monto_estimado_pago) {
            $pago->save() ;
            $this->statusCuota($total, $cuota) ;
            Yii::$app->session->setFlash('success', "Pago guardado") ;
            return true ;
            
        } else {
            Yii::$app->session->setFlash('danger', "Pago no guardado, monto mayor al monto de la cuota") ;
            return false ;
        }
    }

    /**
     * Actualizar status cuota
     * @author Julio Murillo <jmurillo@grudu.org>
     * @param type $total
     * @param CondicionPago $cuota
     */
    public function statusCuota($total, $cuota) {
        
        if ($total == $cuota->monto_estimado_pago) {
            
            $cuota->id_estatus_pago = \common\models\EstatusPago::ESTATUS_PAGO_CANCELADA ;
            $cuota->save() ;
            $this->statusFactura($cuota->id_factura) ;
        } else {
            $cuota->id_estatus_pago = \common\models\EstatusPago::ESTATUS_PAGO_PARCIALMENTE_CANCELADA ;
            $factura                = Factura::findOne($cuota->id_factura) ;
            $factura->id_estatus    = \app\models\EstatusFactura::ESTATUS_FACTURA_PARCIALMENTE_CANCELADA ;
            $factura->save() ;
            $cuota->save() ;
        }
        
    }

    /**
     * Actualizar estatus de factura
     * @param type $idFactura
     * @return boolean
     */
    public function statusFactura($idFactura) {

        $factura   = Factura::findOne($idFactura) ;
        $cuotas    = CondicionPago::find()->where(['id_factura' => $idFactura])->all() ;
        $cancelada = 1 ;
        
        foreach ($cuotas as $value) {
            
            if ($value['id_estatus_pago'] != \common\models\EstatusPago::ESTATUS_PAGO_CANCELADA) {
                $cancelada = 0 ;
            } 
        }
        
        if ($cancelada == 1) {
            $factura->id_estatus = \app\models\EstatusFactura::ESTATUS_FACTURA_CANCELADA ;
            
        } else {
            $factura->id_estatus = \app\models\EstatusFactura::ESTATUS_FACTURA_PARCIALMENTE_CANCELADA ;
        }

        if ($factura->save()) {
            return true ;
        }
        
        return false ;
    }

}

src/web/frontend/views/pagos/add.php
<?php
/* @var $this yii\web\View */

use kartik\widgets\Select2;
use yii\widgets\ActiveForm;
use yii\bootstrap\Html;
use kartik\money\MaskMoney;
use kartik\date\DatePicker;

$this->title                   = 'Pagos' ;
$this->params['breadcrumbs'][] = $this->title ;
?>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-3 col-lg-offset-4">
                            <?php $form = ActiveForm::begin([
                                    ]) ;
                            ?>
                            <label for="n_factura">Buscar N° Factura</label>
                            <?=
                            Select2::widget([
                                'name'    => 'n_factura',
                                'data'    => $data,
                                'size'    => Select2::MEDIUM,
                                'options' => [
                                    'placeholder' => 'Seleccione Factura ...',
                                ],
                                'addon'   => [
                                    'append' => [
                                        'content'  => Html::submitButton('<span class="glyphicon glyphicon-search" aria-hidden="true"></span>', [
                                            'class'       => 'btn',
                                            'title'       => 'Buscar',
                                            'data-toggle' => 'tooltip'
                                        ]),
                                        'asButton' => true
                                    ]
                                ]
                            ]) ;
                            ?>
                        </div>
                        <?php ActiveForm::end() ?>
                    </div>
                    <hr>
                    <?php
                    if ($factura) :
                    ?>
                        <div class="row">
                            <div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4">
                                <label>N° Factura</label>: 
                                <?= $factura->nro_factura ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 col-md-4">
                                <label>Proveedor</label>: 
                                <?php
                                $proveedor = app\models\Proveedor::findOne($factura->id_proveedor);
                                echo $proveedor['nombre'] ?>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <label>Monto Total de Factura</label>
                                <?php
                                $montoFactura = (isset($factura->monto_factura_final)) ? $factura->monto_factura_final : $factura->monto_factura_inicial ;
                                echo $montoFactura ;
                                ?>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <label>Estatus</label>
                                <?php
                                $estatus = common\models\EstatusFactura::findOne($factura->id_estatus);
                                echo $estatus['descripcion'] ?>
                            </div>
                        </div>
                    <hr>
                    <?php
                    endif ;
                    if ($cuotas) :
                    ?>
                        <div class="row">
                            <div class="col-lg-2 col-md-2">
                                <label>Porcentaje de la cuota</label>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <label>Monto de la cuota</label>
                            </div>
                            <div class="col-lg-1 col-md-1">
                                <label>Monto Abonado</label>
                            </div>
                            <div class="col-lg-1 col-md-1">
                                <label>Monto Pendiente</label>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <label>Monto a Pagar</label>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <label>Fecha de pago</label>
                            </div>
                        </div>
                    <?php
                    $i = 0;
                    foreach ($cuotas as $value) :
                        $model[$value['id_cuota']] = $pago[$value['id_cuota']];
                        $i++;
                    ?>
                        <div class="row">
                            <div class="col-lg-2 col-md-2">
                                <?= $value['porcentaje'] ?>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <?= $value['monto_estimado_pago'] ?>
                            </div>
                            <div class="col-lg-1 col-md-1">
                                <?= $monto[$value['id_cuota']]['abonado'] ?>
                            </div>
                            <div class="col-lg-1 col-md-1">
                                <?= $monto[$value['id_cuota']]['pendiente'] ?>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <?= 
                                \yii\helpers\Html::input('text','monto',null,['id_cuota_monto'=>$value['id_cuota'],'id'=>'monto','class'=> "form-control"]);
                                ?>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <?=
                                DatePicker::widget([
                                    'name' => 'fecha',
                                    'options' => [
                                        'id_cuota_fecha' => $value['id_cuota'],
                                        
                                        ],
                                    'pluginOptions' => [
                                        'autoclose'=>true,
                                        'format' => 'yyyy-mm-dd'
                                    ]
                                ]);
                                ?>    
                            </div>
                            <div class="col-lg-2 col-md-1">
                                <?= \yii\helpers\Html::button('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>',['class'=>'btn btn-info cuota','id'=>'plus_cuota','id_cuota'=>$value['id_cuota']]) ?>
                            </div>
                        </div>
                    <br>
                    <?php
                        endforeach;
                    endif;
                    ?>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<?php
$url    = \yii\helpers\Url::to(['pagos/pay']);
$script = <<< JS
    $( ".cuota" ).bind( "click", function() {
        var id_cuota = $( this ).attr( "id_cuota" );
        var monto    = $( 'input[id_cuota_monto='+id_cuota+']' );
        var fecha    = $( 'input[id_cuota_fecha='+id_cuota+']' );
        
        if (fecha.val() == '') {
            alert("Debe ingresar Fecha");
        } else if (monto.val() == ''){
            alert("Debe ingresar Monto");
        } else {
            $.post("$url", { id_cuota:id_cuota,monto:monto.val(), fecha:fecha.val() } ,function(data){
                location.reload();
            });
        }
        
    });
JS;
$this->registerJs($script);
?>

src/web/frontend/views/pagos/index.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */